### ISSUE TITLE
How to add relevant API keys?

### ISSUE THREAD

**Issue by munkk01** [yeti-platform/yeti-docker#16]
Got this up and running but notice a few feeds failing due to invalid or missing API keys.

Do I need to add them in the .env file and they'll be imported at next docker-compose up? Or what do I need to do to get those API keys ingested?

Thank you!

**Comment by sebdraven** [comment]
you can copy the yeti.conf 

`sudo docker cp yeti-tasks:/app/yeti.conf .`

you setup the file conf in local, you store it.

and 

`sudo docker cp yeti.conf yeti-tasks:/app`

`sudo docker compose yeti-tasks restart`

**Comment by munkk01** [comment]
Ah I was one step off from that. I did that for the yeti-api and restarted the entire docker instance which wiped out everything I changed.

I'll give this method a shot. Thank you!

**Comment by munkk01** [comment]
Hmm, I'm all of a sudden having a new error on a new machine that I'm trying to install this on:

```
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe91b548520>: Failed to establish a new connection: [Errno 111] Connection refused')': /_db/_system/_api/database
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe91b897550>: Failed to establish a new connection: [Errno 111] Connection refused')': /_db/_system/_api/database
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe91b548640>: Failed to establish a new connection: [Errno 111] Connection refused')': /_db/_system/_api/database
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe91b548250>: Failed to establish a new connection: [Errno 111] Connection refused')': /_db/_system/_api/database
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe91b5485e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /_db/_system/_api/database
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe91b54b550>: Failed to establish a new connection: [Errno 111] Connection refused')': /_db/_system/_api/database
Traceback (most recent call last):
  File "/app/yetictl/cli.py", line 96, in <module>
    cli()
  File "/root/.cache/pypoetry/virtualenvs/yeti-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/yeti-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/yeti-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.cache/pypoetry/virtualenvs/yeti-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/yeti-9TtSrW0h-py3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/app/yetictl/cli.py", line 29, in create_user
    user = UserSensitive.find(username=username)
  File "/app/core/database_arango.py", line 309, in find
    documents = list(cls._get_collection().find(kwargs, limit=1))
  File "/app/core/database_arango.py", line 889, in _get_collection
    return cls._db.collection(cls._collection_name)
  File "/app/core/database_arango.py", line 137, in collection
    self.connect()
  File "/app/core/database_arango.py", line 67, in connect
    yeti_db = sys_db.has_database(database)
  File "/root/.cache/pypoetry/virtualenvs/yeti-9TtSrW0h-py3.10/lib/python3.10/site-packages/arango/database.py", line 989, in has_database
    return self._execute(request, response_handler)
  File "/root/.cache/pypoetry/virtualenvs/yeti-9TtSrW0h-py3.10/lib/python3.10/site-packages/arango/api.py", line 74, in _execute
    return self._executor.execute(request, response_handler)
  File "/root/.cache/pypoetry/virtualenvs/yeti-9TtSrW0h-py3.10/lib/python3.10/site-packages/arango/executor.py", line 65, in execute
    resp = self._conn.send_request(request)
  File "/root/.cache/pypoetry/virtualenvs/yeti-9TtSrW0h-py3.10/lib/python3.10/site-packages/arango/connection.py", line 281, in send_request
    return self.process_request(host_index, request, auth=self._auth)
  File "/root/.cache/pypoetry/virtualenvs/yeti-9TtSrW0h-py3.10/lib/python3.10/site-packages/arango/connection.py", line 160, in process_request
    raise ConnectionAbortedError(
ConnectionAbortedError: Can't connect to host(s) within limit (3)
```

I made no changes from the previous host install to this one.. not sure why this is happening now.

Proxmox VM:
Ubuntu Server 24.04.04 LTS
Docker installed per the recommended steps at `https://docs.docker.com/engine/install/debian/`
User added to docker group
